FROM nginx:1.25-alpine
LABEL maintainer="MontaRapido <dev@montarapido.com.br>"

# Remove config default do nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copia os arquivos do frontend
COPY . /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
